### PR TITLE
added dependencies: pyyaml, yacs

### PR DESCRIPTION
**Pull request by sugatoray**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged) `0 --> 1`
* [x] Reset the build number to `0` (if the version changed) `NA`
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sugatoray** [comment]
@conda-forge-admin, please rerender

**Comment by sugatoray** [comment]
Closes #22 .

**Comment by mikemhenry** [comment]
@sugatoray is this still a problem?

**Comment by sugatoray** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
